# Generated by Django 4.1.5 on 2023-01-31 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userlistrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('review', models.TextField(blank=True)),
                ('modified_date', models.DateField(default=datetime.date.today)),
                ('author', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=150)),
                ('tag_relation_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_reference', models.IntegerField(default=1)),
                ('created_time', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ListSongRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.list')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
        ),
    ]
